Improved fitness function
rasmusmarak/TOSS pull request #38
Opened 2023-03-30 09:34 UTC by rasmusmarak

2023-03-31 07:59 UTC, rasmusmarak commented
Here is the issue regarding an improved terminating event function for collision with body. #39

2023-03-31 10:01 UTC, gomezzz requested changes
Please try to improve the structure of the code, I don't understand the code at all. You have way too many functions in places where they make no sense.

Ideally, add a folder fitness functions with the following files:
* fitness_function_enums.py - Contains an enum with the names for the different functions
* fitness_function.py - Contains for each of the above enums exactly one function that receives position and time as input and evaluates the fitness according to its scheme and function that returns the respective function
* fitness_function.utils.py - Contains utility functions for the above functions, e.g. estimating the volume covered by trajectory 

The UDP can import the necessary fitness function with something like

```py
from fitness.fitness_function_enums import FitnessFunctions
from fitness.fitness_functions import get_fitness_function

chosen_function = FitnessFunctions.CoveredVolumeFarDistancePenalty

fitness_function = get_fitness_function(chosen_function)

# and later you just call
fitness = fitness_function(position,timesteps)
```

2023-04-03 02:31 UTC, rasmusmarak commented
I have now finished all of the requested changes as well as some general restructuring of the code. Given this, it may appear as a great number of "new changes and code" on the reviewing end, likely as a consequence of the moving of files to new folders and separation of functions into new files for a more logical structure. But hopefully it is a bit more well structured now, especially compared to before. The replacement of the previously used notebook is included in the other PR regarding parallelization (as this feedback concerned both PRs).

2023-04-03 08:36 UTC, gomezzz requested changes
Looks a lot better! Some minor formatting comments and you might want to add some simple tests for a few components to be sure they work as intended and keep doing so. almost there :v:

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +    fitness = np.mean(np.abs(positions[0,:]**2 + positions[1,:]**2 + positions[2,:]**2 -args.problem.target_squared_altitude))
a helper function 

```py
def _compute_squared_distance(arr,constant):
    return np.abs(np.sum(np.pow(arr,2)) - constant)
```

could be useful in a bunch of places in this file

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +    r[r<0] = 0 #removes all positions inside the measurement-zone.
as above, would make it smooth

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +    from fitness_function_utils import estimate_covered_volume
please put all imports at the top of the file

( https://peps.python.org/pep-0008/#imports )

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +    return (CoveredVolume(args,positions,timesteps) + FarDistancePenalty(args,positions,timesteps))
If I am not mistaken , the covered volume is 0 to 1 and the far distance penalty 0 to a lot, so you need to consider some weighting here. I think you can just weight covered volume based on `args.problem.radius_outer_boundings_sphere` probably? :)

2023-04-03 08:36 UTC, gomezzz commented on toss/optimization/udp_initial_condition.py
> +        from trajectory.compute_trajectory import compute_trajectory
imports at the top pls

2023-04-03 08:36 UTC, gomezzz commented on toss/trajectory/compute_trajectory.py
> +    import pykep as pk
(if you want to automate my complaints you could consider using flake :) Just take line 1 - 24 from this https://github.com/aidotse/PASEOS/blob/main/.github/workflows/run_tests.yml#L12 )

2023-04-03 08:36 UTC, gomezzz commented on toss/trajectory/compute_trajectory.py
> +    from toss.trajectory.Integrator import IntegrationScheme
at the top

2023-04-03 08:36 UTC, gomezzz commented on toss/trajectory/compute_trajectory.py
> +    from toss.mesh.mesh_utility import is_outside
🔝

2023-04-03 08:36 UTC, gomezzz commented on toss/trajectory/trajectory_tools.py
> +def get_trajectory_fixed_step(args, list_of_ode_objects: list) -> Union[np.ndarray, np.ndarray]:
this function deserves a test if possible to make sure the intervals are as expected

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_function_utils.py
> +def estimate_covered_volume(positions: np.ndarray) -> float:
A test for this function maybe nice

2023-04-03 08:36 UTC, gomezzz commented on toss/fitness/fitness_functions.py
you might want to consider simple tests for the fitness functions as sanity checks

2023-04-05 12:10 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +        args (dotmap.DotMap): Dotmap with information on radius of outer bounding sphere.
why a dotmap? you only use one float, just pass that? also avoids the very generic `args`

2023-04-05 12:10 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +        args (dotmap.DotMap): Dotmap with information on radius of outer bounding sphere.
as above

2023-04-05 12:10 UTC, gomezzz commented on toss/fitness/fitness_functions.py
>          args (dotmap.DotMap): Dotmap with information on radius of outer bounding sphere.
as above

2023-04-05 12:11 UTC, gomezzz commented on toss/fitness/fitness_functions.py
>          args (dotmap.DotMap): Dotmap with information on total measurable volume and radius of outer bounding sphere.
as above

2023-04-05 12:13 UTC, gomezzz commented on toss/trajectory/compute_trajectory.py
> +sys.path.append("../..")
as in other file, don't mess with user's path 🙏

2023-04-19 14:53 UTC, gomezzz approved these changes
just some minor comments, not sure if they need addressing

2023-04-19 14:53 UTC, gomezzz commented on scripts/trajectory_plot.png
not sure if intentionally added?

2023-04-19 14:53 UTC, gomezzz commented on toss/fitness/fitness_functions.py
> +    distance_squared = distance_squared[distance_squared<0]
How can squared numbers be <0? :)

2023-04-19 14:53 UTC, gomezzz commented on toss/trajectory/equations_of_motion.py
> +    if args.problem.activate_rotation == True:
```suggestion
    if args.problem.activate_rotation:
```

2023-04-29 17:45 UTC, merged